### ISSUE TITLE
can't create correctly the datasource in grafana

### ISSUE THREAD

**Issue by brobeckero** [gbrian/grafana-timelion-datasource#1]
Hello,

I can't seem to access the timelion api from the datasource.

Could you tells me if there is any pre requisite in order to use your datasource ?

elasticsearch version (5.2.2)  and configuration item ?
grafana version (4.4) 

BR
Olivier

**Comment by gbrian** [comment]
Hi @brobeckero,

Sorry forgot about some dark magic needed. As Timelion runs under Kibana it needs some headers on the requests to be present.

This is taken from normal request at Timelion's Kibana interface:

    http://kibana5.sembo.se:5601/api/timelion/run
    ....
    kbn-version:5.3.0
    Content-Type:application/json
    ...

So we need to send the `kbn-version` and `Content-Type`  headers in order to work.
You can test it with postman for example.

Let me know if it worked.
Regards

**Comment by brobeckero** [comment]
Hi,

sorry for my late answer, I was on vacation.

I'm not sure to understand how to configure it on grafana. I don't know
where to indicate the header and the content type.

[image: Images intégrées 1]

moreover, I can't use postman cause my kibana is in a closed area.

BR

2017-07-28 11:29 GMT+04:00 Gustavo Brian <notifications@github.com>:
