### ISSUE TITLE
grafana 6.7.3 support

### ISSUE THREAD

**Issue by afeshti** [gbrian/grafana-timelion-datasource#20]
Hello, I am giving a try to new grafana release 6.7 but I have some problem with the timelion plugin, in fact when you try to save the datasource an http 400 appear:

`{"statusCode":400,"error":"Bad Request","message":"Invalid request payload JSON format"}[
`
actually the payload to the kibana timelion endpoint is something like this:

`sheet=.es%28*%29&time=%5Bobject+Object%5D
`
when you try the same thing on grafana 5 the payload is a json well formed:

`{"sheet":[".es(*)"],"time":{"from":"now-1m","to":"now","interval":"auto","timezone":"Europe/Berlin"}}`

I will dig on code and net looking for a solution, but well, even if I don't see a lot of activity here I tought that giving a shot here was a good idea.

Thank you
AF

**Comment by gbrian** [comment]
Hi @afeshti ,

Glad to know someone still using this plugin. 
Is a looong time without working with grafana so I'm bit outdated about chanhges on the new releases.
As I understand Timelion has changed their API, am I right? Are you using Kibana cloud or o on premise?

Thanks

**Comment by afeshti** [comment]
Hi there! Thank you for feedback. Actually I think the problem it is not on the Kibana side. It is on the Grafana side, using F12 on browser it is possibile to see the bad formed json request:

![image](https://user-images.githubusercontent.com/9715870/80419808-14b6e500-88da-11ea-99f9-eb4d17879fcd.png)

that on the old Grafana 5 was correct:

![image](https://user-images.githubusercontent.com/9715870/80420246-bd654480-88da-11ea-951f-b91322ff6c48.png)

Maybe a compatibility problem? Btw, I am using Kibana 7.6.2.

Again, thank you.
AF

**Comment by afeshti** [comment]
Hi @gbrian, just a note, even with new grafana 7 (beta 1) the problem is present..

**Comment by gbrian** [comment]
Hi @afeshti,
Sorry seems that I forgot to press "comment" button last time 🤦 
I testes and the issue is:
With new versions of Grafana they changed `XHR` by `fetch` and now data object is not properly serialized due to this line in Grafana:

`if (contentType && contentType.toLowerCase() === 'application/json') {`

https://github.com/grafana/grafana/blob/a5b377e701388fe864e85054c3cc9e9fc9518a5d/public/app/core/utils/fetch.ts#L81

This plugin is defining the header as: 

`"Content-Type": "application/json;charset=UTF-8"` 

🤔 probably it will take forever to them to fix that... so let me see if I can do bodge job here in the meantime 😓
